### ISSUE TITLE
Añadir Diviones al Sidebar

### ISSUE THREAD

**Issue by MarioDMC** [MarioDMC/SAC-UNID#72]
Dividir la Sidebar por secciones utilizando dropdowns

1. Apartados (Sin dropdown)

2. Cañones (dropdown)
    2.1 Cañones
    2.2 Entradas

3. Usuarios (dropdown)
   3.1 Usuarios
   3.2 Niveles

4.  Campus (dropdown)
    4.1 Grados
    4.2 Salones
    4.3 Servicios

5.  Configuración    
    5.1 Logs

![image](https://user-images.githubusercontent.com/46493775/67695660-6bffeb00-f973-11e9-9d13-ab6bff57694c.png)

Ejemplos: 

![image](https://user-images.githubusercontent.com/46493775/67696431-dd8c6900-f974-11e9-8bff-1024e0b69631.png)

https://codepen.io/eugen-belz/pen/jwoJLQ/ 

![image](https://user-images.githubusercontent.com/46493775/67696684-4bd12b80-f975-11e9-9b01-981fdc6bd303.png)

https://bootstrapious.com/p/bootstrap-sidebar
https://bootstrapious.com/tutorial/sidebar/index.html

**Comment by AlanSalas** [comment]
me rifo

**Comment by MarioDMC** [comment]
Todavía no le he avisado, aun me falta crear una ultima taréa para que todos puedan tomar una

> me rifo

**Comment by AlanSalas** [comment]
ok

**Comment by MarioDMC** [comment]
https://github.com/MarioDMC/SAC-UNID/pull/74
